name: CD
# Builds, zips, and uploads binaries to a GitHub release when it is published

on:
  release:
    types: [published]

permissions: {}

jobs:
  assets:
    name: Upload release assets

    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: dm.exe
          - os: macos-latest
            target: aarch64-apple-darwin
            bin: dm
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: dm

    runs-on: ${{ matrix.os }}
        
    permissions:
      # contents: read # Required for actions/checkout
      contents: write # Required for uploading release assets
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Install target
        run: rustup target add ${{ matrix.target }}
        
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: Zip binary
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.bin }} ${{ matrix.bin }}
          7z a dm-${{ matrix.target }}.zip ${{ matrix.bin }}
        
      - name: Upload asset
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: dm-${{ matrix.target }}.zip
